# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ACER/UART_F2/UART_F2.srcs/sources_1/ip/fifo_1/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ACER/UART_F2/UART_F2.gen/sources_1/ip/fifo_1/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ACER/UART_F2/UART_F2.gen/sources_1/ip/fifo_1/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ACER/UART_F2/UART_F2.srcs/sources_1/ip/fifo_1/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ACER/UART_F2/UART_F2.gen/sources_1/ip/fifo_1/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ACER/UART_F2/UART_F2.gen/sources_1/ip/fifo_1/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
